jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        lfs: true
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: adopt
        java-version: '21'
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build --stacktrace --scan
    - continue-on-error: true
      name: cache nodes dependencies
      uses: actions/upload-artifact@v3
      with:
        name: cached-localnet
        path: .localnet
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: CI
on:
  repository_dispatch:
    types: trigger-ga___build.yml
